### PR TITLE
Made many changes to the layout, and added some functionality

### PR DESCRIPTION
**Pull request by Meyr991**
1. Files inside the selected folder now appear in a little table below the buttons
2. New confirmation window when renaming files
2.1 Users can deselect files they do not wish to have renamed
2.2 Users can double-click on a file to give it a different name
3. Changed the layout using ttkbootstrap
3.1 Also added a little dark mode button, so I don't flashbang people :)

### CODE REVIEW

**Comment by Meyr991** [comment]
1. The main table now also shows the subfolders and it's children

This causes a problem, because the confirmation page will not show the same thing the main table shows, will fix, marked as draft for now

**Comment by fruitTheory** [comment]
Lovely additions @Meyr991  , While its in draft I'll go over the initial commit to make sure I understand everything and then check up on any updates beyond that. May be slow as I'm bit newer to github and programming.  I also have some ideas to build on top of this functionality later on. Cheers

**Comment by Meyr991** [comment]
Problem with the confirmation table fixed.
If you have any questions about the code I wrote please let me know, I tried to make it as clear as possible, but i'm not too good at that :)

**Review by fruitTheory — APPROVED** [review]
Approved for now, going to merge and tinker with in IDE, there are a few notes to look into, but easier to check with hands on

**Comment by fruitTheory** [comment]
@Meyr991 
Thanks for the contribution <3 there are some really clever solutions. The while loop for file size and many more that stood out👍 -- Still have to deep dive but **really** appreciate it

**Comment by Meyr991** [comment]
I'm happy to help !! 😀

**Pull request merged**
